version: 2
updates:
- package-ecosystem: pip
  directory: "/allure-pytest-il"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/allure-python-commons-il"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/allure-python-commons-il-test"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
