name: build allure python

on:
  pull_request:
    branches:
      - master

jobs:
  pytest-changes:
    name: Collect allure-pytest-il file changes
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.allure-pytest-il }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            allure-pytest-il:
              - allure-pytest-il/**
              - allure-python-commons-il/**
              - allure-python-commons-il-test/**
              - tests/*.py
              - tests/allure_pytest_il/**
  other-changes:
    name: Collect file changes other than allure-pytest-il
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            allure-nose2-il:
              - allure-nose2-il/**
              - allure-python-commons-il/**
              - allure-python-commons-il-test/**
              - tests/*.py
              - tests/allure_nose2/**
            allure-python-commons-il: allure-python-commons-il/**
            allure-python-commons-il-test: allure-python-commons-il-test/**

  lint:
    name: Static check
    runs-on: ubuntu-latest
    needs: [pytest-changes, other-changes]
    if: ${{ needs.pytest-changes.outputs.changed == 'true' || needs.other-changes.outputs.packages != '[]' }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install linting packages
        run: pip install -r ./requirements/linting.txt

      - name: Linting the codebase
        run: poe linter

  test-pytest:
    name: Test allure-pytest-il
    runs-on: ubuntu-latest
    needs: [pytest-changes]
    if: ${{ needs.pytest-changes.outputs.changed == 'true' }}
    strategy:
      matrix:
        python-version: ["3.8"]
        pytest-version: ["7.*", "8.*"]
        exclude:
          - python-version: "3.8"
            pytest-version: "8.*"
    env:
      TEST_TMP: /tmp
      ALLURE_INDENT_OUTPUT: yep
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install packages
        run: |
          pip install ./allure-python-commons-il \
            ./allure-python-commons-il-test \
            ./allure-pytest-il \
            pytest==${{ matrix.pytest-version }} \
            -r ./requirements/testing.txt \
            -r ./requirements/testing/allure-pytest-il.txt

      - name: Test allure-pytest-il
        working-directory: allure-pytest-il
        run: poe tests

  test-others:
    name: Test other packages
    runs-on: ubuntu-latest
    needs: [other-changes]
    if: ${{ needs.other-changes.outputs.packages != '[]' }}
    strategy:
      matrix:
        package: ${{ fromJSON(needs.other-changes.outputs.packages) }}
        python-version: ["3.8"]
        exclude:
          - package: allure-pytest-il
    env:
      TEST_TMP: /tmp
      ALLURE_INDENT_OUTPUT: yep
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install packages
        run: |
          pip install ./allure-python-commons-il \
            ./allure-python-commons-il-test \
            ./${{ matrix.package }} \
            -r ./requirements/testing.txt \
            -r ./requirements/testing/${{ matrix.package }}.txt

      - name: Test ${{ matrix.package }}
        working-directory: ${{ matrix.package }}
        run: poe tests
